spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.vjfshfzbkwgkikqodguh
spring.datasource.password=asdwdsdf15sdf4sdf54asd11asd

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true